### ISSUE TITLE
Deprication Warning?

### ISSUE THREAD

**Issue by johnmastri** [zingchart/zingtouch#10]
Haven't had these warning pop up until today - any ideas?

Performing operations that require explicit user interaction on touchend events that occur as part of a scroll is deprecated and will be removed in M55, around November 2016. See https://www.chromestatus.com/features/5649871251963904 for more details.

Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by mike-schultz** [comment]
What environment are you seeing these warnings? Are you seeing this whenever you use zingtouch or is it under certain use cases?

Adding this to the discussion as well: 

https://docs.google.com/document/d/1oF1T3O7_E4t1PYHV6gyCwHxOi3ystm0eSL5xZu7nvOg/edit#heading=h.qq59ev3u8fba

**Comment by mike-schultz** [comment]
Adding these to the discussion as well: 

**Touch gesture intervention:**
https://docs.google.com/document/d/1oF1T3O7_E4t1PYHV6gyCwHxOi3ystm0eSL5xZu7nvOg/edit#heading=h.qq59ev3u8fba

Pointer events in chrome 55+ could be potentially useful here if touch events become problematic.
https://developers.google.com/web/updates/2016/10/pointer-events
