### ISSUE TITLE
Panning and rotating the same element

### ISSUE THREAD

**Issue by MaximeDesRoches** [zingchart/zingtouch#12]
Hey, thanks for the amazing library !

Is there any way to make the pan, pinch and rotate events work together ?

**Comment by mike-schultz** [comment]
You can attach as many listeners to a single object as you want, but they will only fire when that specific gesture is being performed. This does mean that multiple gestures may fire simultaneously, such as a 2-finger pinch and 2-finger rotate. It would be up to the end-developer to make the decision of what listener is appropriate at that time. The library does not perform any deterministic guessing as to what the touch gesture is supposed to be - more flexibility. 

The only issue I do see right now is the rotate gesture does not currently have a parameter for selecting one or two fingers; it simply listens for both. Which could or could not be a bad thing :)

**Comment by MaximeDesRoches** [comment]
Ok, thanks, I'll se what I can do then.
