### ISSUE TITLE
Prevent Default for Left / Right Swipes Only (Browser History Issue)

### ISSUE THREAD

**Issue by markadrake** [zingchart/zingtouch#14]
Thought I might use your touch library here to create my own version of a slider but noticed I'm having some issues in Google Chrome because a swipe left or right will also cause the browser to go back or forward (respectively) in history.

This behavior is prevented by the default value of `preventDefault` - however if this is set to true on an element that takes up a large percentage of the viewport (say 100%) then it also prevents a user from scrolling further down the page.

If anyone has experimented with simply preventing the default (history) for right and left swipes only please let me know. Thanks!

**Comment by markadrake** [comment]
Thinking the alternative here is to leave `preventDefault` off like it is by default, but wire a pan up/down event to scroll the body of the page. But now I'm using `scrollBy(x, y)` and it's jumpy instead of smooth. Probably just making more of a hassle than it's worth. Love to hear somebody else's feedback just in case they've tried it though.

**Comment by mike-schultz** [comment]
One approach you could take is to set the region's preventDefault to false, but to dynamically call `preventDefault()` on the original event when you want it to stop. 

Something along the lines of...

```js
const touchRegion = new ZingTouch.Region(container, true, false);
const blockScrolling = false;

touchRegion.bind(target, 'pan', function(e){

  // Change conditional logic here
  
  if (blockScrolling) {
    // The original event is stored under this path.
    (e.detail.events).forEach( _e => _e.originalEvent.preventDefault());
    // perform your slider logic here
  } 
});

// Reset the counter when the input leaves the screen.
touchRegion.on('touchend', function(e){
 blockScrolling = false;
});
```

You'll need to figure out when you want the scrolling to be stopped manually. Possibly detect if the user has been in a horizontal motion, rather than a vertical scrolling motion.

**Comment by markadrake** [comment]
I was able to use your suggestion in this way Mike. Essentially I pick a range of angles that are appropriate for left / right (next / prev) movement, and for others I allow scrolling to continue through. I initialize the region with a false flag for `preventDefault`.

```
region.bind(element, "pan", function(e) {
	console.log("panning");

	let angle = e.detail.data[0].directionFromOrigin;

	if ((angle >= 315 && angle <= 360) || (angle <= 45 && angle >= 0)) {
		direction = "right";
		(e.detail.events).forEach(_e => _e.originalEvent.preventDefault());
		return;
	}
	else if (angle >= 135 && angle <= 225) {
		direction = "left";
		(e.detail.events).forEach(_e => _e.originalEvent.preventDefault());
		return;
	}
	else if (angle <= 135) {
		direction = "up";
	} else {
		direction = "down";
	}
});
```

Thank you for your suggestion. Especially for the hint at multiple events needed to have preventDefault called.

**Comment by kklepper** [comment]
Thank you very much! 

See https://stackoverflow.com/questions/64452426/zingtouch-how-to-call-different-urls-with-both-mouse-and-finger-swipe-gestures/64452427#64452427
