### ISSUE TITLE
Swipe event isn't triggered if `preventDefault` is set to false. [Chrome running on Android Device]

### ISSUE THREAD

**Issue by markadrake** [zingchart/zingtouch#15]
If you initialize a region `ZingTouch.Region(element, capture, preventDefault, id)` with `preventDefault: false` the swipe event doesn't seem to trigger at all. 

This is happening on a mobile Android device running Chrome. 

Please let me know if there is anything wrong with the following example: http://codepen.io/markadrake/pen/PbVXZe

I'm simply doing a `console.log` to verify this functionality.

**Comment by mike-schultz** [comment]
I believe this is related to a recent chrome 55 addition which breaks traditional touch action: https://developers.google.com/web/updates/2016/10/touch-action . Hammer.js looks to be having this issue as well. I'll spend some time trying to figure out a solution, but feel free to share any knowledge you find as well.

**Comment by mike-schultz** [comment]
Hey @markadrake , I had some time to take a look at it and it is indeed a pointer events issue in the newest chrome. I don't have a fix for this yet, but if you need an immediate fix you can disable pointer events by just setting this if statement to become false: https://github.com/zingchart/zingtouch/blob/master/src/core/classes/Region.js#L62 . 

PointerEvents are crucial to the Edge browser, so disabling them isn't a long-term option. Before I implement any browser-sniffing, there might be a way to handle pointer events nicely with chrome

**Comment by mike-schultz** [comment]
should be fixed for now in 6ada783 but disallowing pointer events if touchEvents exist. I'll have a build out as soon as a couple other PRs and issues are resolved.

**Comment by Kris-B** [comment]
Hi @mike-schultz 
any news about this chrome issue? do you plan a release?

Chris

**Comment by mike-schultz** [comment]
Hey @Kris-B , the PR I was waiting on got stale, but I went ahead and pushed ahead a release including the workaround that I did to avoid pointer events in chrome.

**Comment by Kris-B** [comment]
any thanks!

;-)
