### ISSUE TITLE
Mobile Browser Syntax Error

### ISSUE THREAD

**Issue by danielwilson654** [zingchart/zingtouch#21]
Version 1.04 works with firefox's and chrome's responsive design modes but fails to work on mobile browsers. I tested IOS Safari and Blackberry's native browser. I wasn't able to get browser side debugging working for Safari but my Blackberry reports the following error at line 8 pf zingtouchmin.js

> SyntaxError: Expected an identifier but found "i" instead

I observed this same issue with the master build a few weeks back. I will revert back to 1.0.3 until this is resoved.

**Comment by mike-schultz** [comment]
Just for clarification, it does work on mobile chrome + safari, but does not on blackberry? Could you tell me what versions you are testing on?

**Comment by danielwilson654** [comment]
It fails on IOS Safari, Blackberry's native browser, and Chrome's mobile browser. The library works fine on all desktop browsers I have tested. 

I don't have a mac so I couldn't remote test IOS Safari to see where the issue was. I'm assuming it has the same issue as the blackberry for the symptoms are the same on both devices. The Library fails to load.

**Comment by danielwilson654** [comment]
I used the Zingtouch Expand_Pinch Pen I made earlier to test this. I found 1.03 worked fine on all devices tested. 1.04 worked only IOS 10.2 (up to date). It failed to work on an ipad running IOS 9.3.5.

I first observed this issue with a master build I downloaded on Feb 21 2016.

**Comment by mike-schultz** [comment]
I can't seem to replicate this issue on an iphone running 10.2, and I only have access to 9.3 on the iOS simulator (can't replicate it there either). I did test it on a couple android devices running 54-54 chrome but didn't see any issues there.

Are you able to give a line number on an unminifed build of v.1.0.4 + to help track down the error?

**Comment by danielwilson654** [comment]
Thanks for trying Mike. bellow is the error and line 8. I used zingtouch.min.js of 1.04 because it seemed zingtouch.js is actually the minified version. Please correct me if I am wrong.

`SyntaxError: Expected an identifier but found 'i' instead zingtouch.min.js: 8`

`if(n[r])return n[r].exports; let i=n[r]={exports: {}, id: r, loaded: !1}; return e[r].call(i.exports, i, i.exports, t), i.loaded=!0, i.exports;`

I hope this is an easy fix because I would love to test out the fixes you have made since 1.03.

**Comment by pitAlex** [comment]
I can confirm its happening to me too. In mac chrome browser, the 'i' error happens when I have 2 elements with a tap event, one element is inside the other.

**Comment by danielwilson654** [comment]
@pitAlex Thanks for the info. Does the error occur if you use the 1.0.3 library?

**Comment by mike-schultz** [comment]
@pitAlex I believe that issue is related to #22 which is currently fixed on the master branch. I just made a release for that fix (1.0.5).

@danielwilson654 Could you re-verify your issue with 1.0.5?  I recall you stating it was different from the #22 fix, but want to make sure it exists before keeping this issue open.

**Comment by danielwilson654** [comment]
@mike-schultz Sure thing.

**Comment by mike-schultz** [comment]
Also if it helps, `zingtouch.js` should be unminified now in the /dist folder.

**Comment by danielwilson654** [comment]
Fixed! Thanks for that. Backwards comparability is important for the project I'm working on.

I'll now use 1.0.5 to test your fix for #19 and hopefully get that one closed too.
