### ISSUE TITLE
Uncaught ReferenceError: i is not defined

### ISSUE THREAD

**Issue by hermanho** [zingchart/zingtouch#22]
When there are two event bindings in DOM tree, it throw error

> Uncaught ReferenceError: i is not defined

Example, error will throw when tap on the green button
https://jsfiddle.net/hermanho/nbfmdxpm/

**Comment by danielwilson654** [comment]
Could be related to #21...

**Comment by mike-schultz** [comment]
Thanks, fix will be in the next release
