### ISSUE TITLE
Pan on IE issue

### ISSUE THREAD

**Issue by DeerBeer** [zingchart/zingtouch#28]
Hi,

I have issue on IE version 11.483
have one Pan gesture and on moving with mouse I receive:

SCRIPT445: Object doesn't support this action
around line 1001 in zingtouch.js
`
      var newEvent = new CustomEvent(binding.gesture.getId(), {
        detail: data,
        bubbles: true,
        cancelable: true
      });
`

**Comment by mike-schultz** [comment]
Hey there,

We currently do not have plans to support IE as there are numerous issues that arise from pointer-events and as this library is more focused towards mobile browsers than desktop.
