### ISSUE TITLE
Unable to Import zingtouch to component. 

### ISSUE THREAD

**Issue by LmKupke** [zingchart/zingtouch#31]
I am currently trying to import zingtouch as an ES6 module but it doesn't seem to be recognized when importing. 

![image](https://user-images.githubusercontent.com/7860541/30663092-7aca60ca-9e17-11e7-8f20-9eae939ae0db.png)

![image](https://user-images.githubusercontent.com/7860541/30663575-16b993f6-9e19-11e7-9e7c-44630e062822.png)

I am currently using webpack 3 with my Angular 4 project.

**Comment by mike-schultz** [comment]
#36 related
