### ISSUE TITLE
Custom Expand Gesture causes it to be counted as a Pinch

### ISSUE THREAD

**Issue by kozelkral** [zingchart/zingtouch#37]
I'm using custom Expand and Pinch gestures with a set threshold in order to account for some finger movement during a two-finger tap and keep it from triggering either gesture on accident.

I created the custom Expand Gesture with the following code:
`var expandGesture = new ZingTouch.Expand({ threshold: 5 })`
`myRegion.register('newExpand', expandGesture)`
`myRegion.bind(touchArea, 'newExpand', handlerFunc)`

What happens then is that everything is considered a Pinch.

The problem obviously arises from the `if...else` in `Distance.move()` where the only acceptable `type` value for Expand is `expand` and everything else falls into the `else` clause, which is for Pinch.

The best solution for my particular problem would be a threshold only for the start of a Pinch or Expand gesture, but I haven't thought of a good way to achieve that, and it is beyond the scope of this issue.

**Comment by mike-schultz** [comment]
@kozelkral Thanks for finding this. I just changed the if to look at the constructor, rather than the named 'newExpand'. I'll be putting out a release this week
