### ISSUE TITLE
ZingTouch.Expand doesn't emit any events

### ISSUE THREAD

**Issue by hackhat** [zingchart/zingtouch#53]
const zingPinch = new ZingTouch.Pinch({});
    const zingExpand = new ZingTouch.Expand({});
    zingTouchActiveRegion.bind(this.canvasElement, zingExpand, (e) => {
      // never fired!
      alert(JSON.stringify(e.detail))
    });
    zingTouchActiveRegion.bind(this.canvasElement, zingPinch, (e) => {
      // fires on pinch!
    });

Not sure why the Expand doesn't work but the Pinch works

But if I remove the pinch

    zingTouchActiveRegion.bind(this.canvasElement, zingExpand, (e) => {
      alert(JSON.stringify(e.detail))
    });

the event emitted is `e.detail.distance` instead of `e.detail.expand` as stated in the docs. https://zingchart.github.io/zingtouch/docs/#expand

**Comment by mvanderkamp** [comment]
This is a bug. See issue #45. I fixed this in PR #48 by consolidating Pinch, Expand, and Distance.

**Comment by hackhat** [comment]
Ah cool. thanks
