### ISSUE TITLE
mobile safari: can't video seek if the video is inside a swipable container

### ISSUE THREAD

**Issue by Mboulianne** [zingchart/zingtouch#56]
See fiddle https://jsfiddle.net/zd9etz70/37/

When I'm registering the swipe handler, I can't seek anymore in my video.
When I'm not registering it (comment the code) everything work as expected.

ios version 11.4.1

**Comment by Mboulianne** [comment]
The same issue happen with panning.
https://jsfiddle.net/zd9etz70/47/

Comment code on and off on this fiddle
Open https://jsfiddle.net/zd9etz70/37/show on mobile safari
Observe

Any suggestion^

**Comment by mvanderkamp** [comment]
Have you tried setting preventDefault to false when you declare the region?

**Comment by Mboulianne** [comment]
Yeah sorry I forgot to update my ticket.  I did put preventDefault to false and everything works now

Thank you :D
