### ISSUE TITLE
mouse support for Rotate gesture

### ISSUE THREAD

**Issue by vvsraju04** [zingchart/zingtouch#6]
ZingTouch's Rotate gesture works very well with touch capable devices . Could we have mouse support as well for this similar to tap ( click ) . We can have Rotate gesture with mouse dragging to rotate in mouse enabled devices to behave as two finger touch rotate .

**Comment by mike-schultz** [comment]
I think that could be possible. The only issue would be where to designate the pivot point in relation to the mouse input - probably the center of the target element. I'll play around with the idea a bit.

**Comment by mike-schultz** [comment]
@vvsraju04 Implemented one-finger rotate in v.1.0.1. I just had to extend the functionality a little for the rotate function to accept a single input. It's usable on both desktop and touch capable devices. See: https://github.com/zingchart/zingtouch/releases/tag/1.0.1

**Comment by mike-schultz** [comment]
![http://i.giphy.com/26BRqwJE79eJuSlWg.gif](http://i.giphy.com/26BRqwJE79eJuSlWg.gif)

**Comment by vvsraju04** [comment]
Thank you @mike-schultz . Works perfectly .
