### ISSUE TITLE
Is this project still actively maintained

### ISSUE THREAD

**Issue by whoacowboy** [zingchart/zingtouch#69]
I love this library and was wondering if it is still actively maintained? 

Are you looking for people to help maintain it?

**Comment by operator888** [comment]
I have the same question.. is this project still active?

**Comment by mike-schultz** [comment]
@whoacowboy @operator888 Hi there - we're currently not maintaining this project as we don't have the bandwidth nor are using it internally at the moment. You are welcome to develop and pull request any fixes and features - I'll have the team monitor this repository as well.

**Comment by whoacowboy** [comment]
@mike-schultz I have forked it and have been using it on our site. I will clean up what I am working on and submit a PR. I have a couple questions. 

### What are you using internally instead? 

### Do you have the images for the home page read me?

http://demos.zingchart.com/assets/zingtouch-docs/region.png
http://demos.zingchart.com/assets/zingtouch-docs/parent-region.png
http://demos.zingchart.com/assets/zingtouch-docs/multiple-regions.png
http://demos.zingchart.com/assets/zingtouch-docs/tap.gif
http://demos.zingchart.com/assets/zingtouch-docs/swipe.gif
http://demos.zingchart.com/assets/zingtouch-docs/pinch.gif
http://demos.zingchart.com/assets/zingtouch-docs/expand.gif
http://demos.zingchart.com/assets/zingtouch-docs/pan.gif
http://demos.zingchart.com/assets/zingtouch-docs/rotate.gif

**Comment by mike-schultz** [comment]
Zingtouch was originally intended to replace our touch system in our ZingChart library but development decided to go another directly due to the way the code was created. I'll see if I can dig up those images and fix the site.

**Comment by pscheit** [comment]
@mike-schultz what direction? no mobile touch system at all?

**Comment by zingsoftadmin** [comment]
@whoacowboy We have recently got resources back on ZingTouch and will continue to support this repository as best we can. We are open to adding maintainers as well!

**Comment by whoacowboy** [comment]
@zingsoftadmin I'd be up for helping out.

**Comment by damntrecky** [comment]
@whoacowboy I have sent you an Maintainer access request.
